import {
    faCarrot,
    faShrimp,
    faStroopwafel,
    faCakeCandles,
    faBowlRice,
    faBlender,
    faHeart,
    faCartShopping,
    faShower,
    faLeaf,
    faMotorcycle,
    faHands,
    faBaby,
    faTruckMonster,
    faTablets,
    faPepperHot,
    faHouse,
    faMugSaucer,
    faTaxi,
    faSmoking,
    faKitchenSet,
    faGamepad,
    faPersonDigging,
    faCookieBite,
    faVenusMars,
    faShieldDog,
    faPiggyBank,
    faMoneyBillWave,
    faCar,
    faCarBurst,
    faAddressBook,
    faGraduationCap,
    faMoneyCheck,
    faMoneyBill,
    faBoxesStacked,
    faCreditCard,
} from "@fortawesome/free-solid-svg-icons";
const iconList = [
    { id: "icon_3d2b1059968c5", name: "stroopwafel", icon: faStroopwafel },
    { id: "icon_aa90343dc3d49", name: "shrimp", icon: faShrimp },
    { id: "icon_46c261a2f21c6", name: "carrot", icon: faCarrot },
    { id: "icon_eac2220d20035", name: "pepper-hot", icon: faPepperHot },
    { id: "icon_26efbb15df5d", name: "cake-candles", icon: faCakeCandles },
    { id: "icon_9cc826a1cbb34", name: "bowl-rice", icon: faBowlRice },
    { id: "icon_1bef134391a78", name: "blender", icon: faBlender },
    { id: "icon_595d83bcf5eb9", name: "heart", icon: faHeart },
    { id: "icon_a86a8bd5b074c", name: "cart-shopping", icon: faCartShopping },
    { id: "icon_ebef9835b1d1d", name: "shower", icon: faShower },
    { id: "icon_84c0d58e8bcf2", name: "leaf", icon: faLeaf },
    { id: "icon_3a26ecaa132d4", name: "motorcycle", icon: faMotorcycle },
    { id: "icon_e43e9cb5b1f5d", name: "hands", icon: faHands },
    { id: "icon_f1d4ea5f99eae", name: "baby", icon: faBaby },
    { id: "icon_0110a629f5b41", name: "truck-monster", icon: faTruckMonster },
    { id: "icon_a1db0aa23e7d6", name: "tablets", icon: faTablets },
    { id: "icon_ffe9c8be4468f", name: "house", icon: faHouse },
    { id: "icon_7177105e8bfac", name: "mug-saucer", icon: faMugSaucer },
    { id: "icon_a7141853150fc", name: "taxi", icon: faTaxi },
    { id: "icon_26b2dfe1a379e", name: "smoking", icon: faSmoking },
    { id: "icon_4afe7d96b1f5f", name: "kitchen-set", icon: faKitchenSet },
    { id: "icon_ed628d025c328", name: "gamepad", icon: faGamepad },
    { id: "icon_24784907c9d4c", name: "person-digging", icon: faPersonDigging },
    { id: "icon_b1367af059b4e", name: "cookie-bite", icon: faCookieBite },
    { id: "icon_13c4d90d1540e", name: "venus-mars", icon: faVenusMars },
    { id: "icon_6aeab39030822", name: "shield-dog", icon: faShieldDog },
    { id: "icon_ee7ba52eabe67", name: "piggy-bank", icon: faPiggyBank },
    { id: "icon_1224a12d6beb1", name: "money-bill-wave", icon: faMoneyBillWave },
    { id: "icon_1224a12d6beb2", name: "car", icon: faCar },
    { id: "icon_1224a12d6beb3", name: "car-burst", icon: faCarBurst },
    { id: "icon_1224a12d6beb4", name: "address-book", icon: faAddressBook },
    { id: "icon_1224a12d6beb5", name: "graduation-cap", icon: faGraduationCap },
    { id: "icon_1224a12d6beb6", name: "money-check", icon: faMoneyCheck },
    { id: "icon_1224a12d6beb7", name: "money-bill", icon: faMoneyBill },
    { id: "icon_1224a12d6beb8", name: "boxes-stacked", icon: faBoxesStacked },
    { id: "icon_1224a12d6beb9", name: "credit-card", icon: faCreditCard },
];
export default iconList;
